### PR TITLE
Fixed removed config condition

### PR DESCRIPTION
**Pull request by NFSS10**
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-sdk-components-vue/pull/32#discussion_r517258774 |
| Dependencies | -- |
| Decisions | Added missing config condition |
| Animated GIF | -- |

### CODE REVIEW

**Comment by gcandal** [comment]
@NFSS10 did you see https://github.com/ripe-tech/ripe-sdk-components-vue/pull/32#discussion_r517258774 ?

**Comment by NFSS10** [comment]
> 
> 
> @NFSS10 did you see [#32 (comment)](https://github.com/ripe-tech/ripe-sdk-components-vue/pull/32#discussion_r517258774) ?

Yes.
Wasn't this PR changes what you meant?

**Comment by NFSS10** [comment]
> 
> 
> > @NFSS10 did you see [#32 (comment)](https://github.com/ripe-tech/ripe-sdk-components-vue/pull/32#discussion_r517258774) ?
> 
> Yes.
> Wasn't this PR changes what you meant?

**Review by gcandal — CHANGES_REQUESTED** [review]
Ifs on clients

**Review by gcandal — APPROVED** [review]

**Comment by gcandal** [comment]
@NFSS10 all of this can now be backported right?

**Comment by NFSS10** [comment]
> @NFSS10 all of this can now be backported right?

If the implementation is good, yes I will start the backport to components-react

**Review by joamag — APPROVED** [review]

**Comment by joamag** [comment]
@NFSS10 Let's back-port this

**Pull request merged**
